2019-02-28 11:48:44.329 INFO  CategoriaServiceTest.testFindAll:41 - Testing findAll ...
2019-02-28 11:48:44.329 INFO  CategoriaServiceTest.testFindAll:41 - Testing findAll ...
2019-02-28 11:48:45.854 INFO  CategoriaServiceTest.testFindAll:68 - Test testFindAll finished.

2019-02-28 11:48:45.854 INFO  CategoriaServiceTest.testFindAll:68 - Test testFindAll finished.

2019-02-28 11:48:57.753 INFO  CategoriaServiceTest.testFindById:25 - Testing findById ...
2019-02-28 11:48:57.753 INFO  CategoriaServiceTest.testFindById:25 - Testing findById ...
2019-02-28 11:48:57.776 INFO  CacheManager.createCache:45 - Cache categorias <class java.lang.Integer,class com.fgc.futbuy.model.Categoria> created. 
2019-02-28 11:48:57.776 INFO  CacheManager.createCache:45 - Cache categorias <class java.lang.Integer,class com.fgc.futbuy.model.Categoria> created. 
2019-02-28 11:48:57.777 DEBUG UsuarioServiceImpl.findById:42 - Fallo cache: 1
2019-02-28 11:48:57.777 DEBUG UsuarioServiceImpl.findById:42 - Fallo cache: 1
2019-02-28 11:48:58.943 ERROR CategoriaServiceTest.testFindById:34 - id = 1
com.fgc.futbuy.exceptions.DataException: null
	at com.fgc.futbuy.service.impl.CategoriaServiceImpl.findById(CategoriaServiceImpl.java:54) ~[bin/:?]
	at com.fgc.futbuy.service.CategoriaServiceTest.testFindById(CategoriaServiceTest.java:30) [bin/:?]
	at com.fgc.futbuy.service.CategoriaServiceTest.main(CategoriaServiceTest.java:90) [bin/:?]
Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:835) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:455) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:240) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:207) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[?:1.8.0_181]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[?:1.8.0_181]
	at com.fgc.futbuy.dao.util.ConnectionManager.getConnection(ConnectionManager.java:35) ~[bin/:?]
	at com.fgc.futbuy.service.impl.CategoriaServiceImpl.findById(CategoriaServiceImpl.java:48) ~[bin/:?]
	... 2 more
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_181]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_181]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_181]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:91) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:152) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:955) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:825) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:455) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:240) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:207) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[?:1.8.0_181]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[?:1.8.0_181]
	at com.fgc.futbuy.dao.util.ConnectionManager.getConnection(ConnectionManager.java:35) ~[bin/:?]
	at com.fgc.futbuy.service.impl.CategoriaServiceImpl.findById(CategoriaServiceImpl.java:48) ~[bin/:?]
	... 2 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[?:1.8.0_181]
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source) ~[?:1.8.0_181]
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) ~[?:1.8.0_181]
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) ~[?:1.8.0_181]
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[?:1.8.0_181]
	at java.net.PlainSocketImpl.connect(Unknown Source) ~[?:1.8.0_181]
	at java.net.SocksSocketImpl.connect(Unknown Source) ~[?:1.8.0_181]
	at java.net.Socket.connect(Unknown Source) ~[?:1.8.0_181]
	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:155) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:65) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:152) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:955) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:825) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:455) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:240) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:207) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[?:1.8.0_181]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[?:1.8.0_181]
	at com.fgc.futbuy.dao.util.ConnectionManager.getConnection(ConnectionManager.java:35) ~[bin/:?]
	at com.fgc.futbuy.service.impl.CategoriaServiceImpl.findById(CategoriaServiceImpl.java:48) ~[bin/:?]
	... 2 more
2019-02-28 11:48:58.943 ERROR CategoriaServiceTest.testFindById:34 - id = 1
com.fgc.futbuy.exceptions.DataException: null
	at com.fgc.futbuy.service.impl.CategoriaServiceImpl.findById(CategoriaServiceImpl.java:54) ~[bin/:?]
	at com.fgc.futbuy.service.CategoriaServiceTest.testFindById(CategoriaServiceTest.java:30) [bin/:?]
	at com.fgc.futbuy.service.CategoriaServiceTest.main(CategoriaServiceTest.java:90) [bin/:?]
Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:835) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:455) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:240) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:207) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[?:1.8.0_181]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[?:1.8.0_181]
	at com.fgc.futbuy.dao.util.ConnectionManager.getConnection(ConnectionManager.java:35) ~[bin/:?]
	at com.fgc.futbuy.service.impl.CategoriaServiceImpl.findById(CategoriaServiceImpl.java:48) ~[bin/:?]
	... 2 more
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_181]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_181]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_181]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:91) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:152) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:955) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:825) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:455) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:240) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:207) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[?:1.8.0_181]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[?:1.8.0_181]
	at com.fgc.futbuy.dao.util.ConnectionManager.getConnection(ConnectionManager.java:35) ~[bin/:?]
	at com.fgc.futbuy.service.impl.CategoriaServiceImpl.findById(CategoriaServiceImpl.java:48) ~[bin/:?]
	... 2 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[?:1.8.0_181]
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source) ~[?:1.8.0_181]
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) ~[?:1.8.0_181]
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) ~[?:1.8.0_181]
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[?:1.8.0_181]
	at java.net.PlainSocketImpl.connect(Unknown Source) ~[?:1.8.0_181]
	at java.net.SocksSocketImpl.connect(Unknown Source) ~[?:1.8.0_181]
	at java.net.Socket.connect(Unknown Source) ~[?:1.8.0_181]
	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:155) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:65) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:152) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:955) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:825) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:455) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:240) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:207) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[?:1.8.0_181]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[?:1.8.0_181]
	at com.fgc.futbuy.dao.util.ConnectionManager.getConnection(ConnectionManager.java:35) ~[bin/:?]
	at com.fgc.futbuy.service.impl.CategoriaServiceImpl.findById(CategoriaServiceImpl.java:48) ~[bin/:?]
	... 2 more
2019-02-28 11:48:59.001 INFO  CategoriaServiceTest.testFindById:37 - Test testFindById finished.

2019-02-28 11:48:59.001 INFO  CategoriaServiceTest.testFindById:37 - Test testFindById finished.

